sudo: required

language: go

go:
  - 1.8

services:
  - docker

before_install:
  - docker login --username "$DOCKER_HUB_USERNAME" --password "$DOCKER_HUB_PASSWORD"

script:
  - docker build --no-cache -t celestialstats/logreceiver:latest .

after_success:
  - docker push celestialstats/logreceiver:latest
